
export const countries = [
    { label: 'Afghanistan (؋-Afghani) - AFG' },
    { label: 'Albania (Lek-Albanian lek) - ALB' },
    { label: 'Algeria (د.ج-Algerian dinar) - DZA' },
    { label: 'Andorra (€-Euro) - AND' },
    { label: 'Angola (Kz-Angolan kwanza) - AGO' },
    { label: 'Antigua and Barbuda (EC$-Eastern Caribbean dollar) - ATG' },
    { label: 'Argentina ($-Argentine peso) - ARG' },
    { label: 'Armenia (֏-Armenian dram) - ARM' },
    { label: 'Australia ($-Australian dollar) - AUS' },
    { label: 'Austria (€-Euro) - AUT' },
    { label: 'Azerbaijan (₼-Azerbaijani manat) - AZE' },
    { label: 'Bahamas ($-Bahamian dollar) - BHS' },
    { label: 'Bahrain (BD-Bahraini dinar) - BHR' },
    { label: 'Bangladesh (৳-Bangladeshi taka) - BGD' },
    { label: 'Barbados ($-Barbadian dollar) - BRB' },
    { label: 'Belarus (Br-Belarusian ruble) - BLR' },
    { label: 'Belgium (€-Euro) - BEL' },
    { label: 'Belize (BZ$-Belize dollar) - BLZ' },
    { label: 'Benin (XOF-West African CFA franc) - BEN' },
    { label: 'Bhutan (Nu.-Bhutanese ngultrum) - BTN' },
    { label: 'Bolivia (Bs-Bolivian boliviano) - BOL' },
    { label: 'Bosnia and Herzegovina (KM-Bosnia and Herzegovina convertible mark) - BIH' },
    { label: 'Botswana (P-Botswana pula) - BWA' },
    { label: 'Brazil (R$-Brazilian real) - BRA' },
    { label: 'Brunei (B$-Brunei dollar) - BRN' },
    { label: 'Bulgaria (лв.-Bulgarian lev) - BGR' },
    { label: 'Burkina Faso (XOF-West African CFA franc) - BFA' },
    { label: 'Burundi (FBu-Burundian franc) - BDI' },
    { label: 'Cabo Verde (Esc-Cape Verdean escudo) - CPV' },
    { label: 'Cambodia (៛-Cambodian riel) - KHM' },
    { label: 'Cameroon (XAF-Central African CFA franc) - CMR' },
    { label: 'Canada ($-Canadian dollar) - CAN' },
    { label: 'Central African Republic (XAF-Central African CFA franc) - CAF' },
    { label: 'Chad (XAF-Central African CFA franc) - TCD' },
    { label: 'Chile ($-Chilean peso) - CHL' },
    { label: 'China (¥-Chinese yuan) - CHN' },
    { label: 'Colombia ($-Colombian peso) - COL' },
    { label: 'Comoros (CF-Congolese franc) - COM' },
    { label: 'Congo, Democratic Republic of the (FC-Congolese franc) - COD' },
    { label: 'Congo, Republic of the (FC-Congolese franc) - COG' },
    { label: 'Costa Rica (₡-Costa Rican colón) - CRI' },
    { label: 'Croatia (kn-Croatian kuna) - HRV' },
    { label: 'Cuba ($-Cuban peso) - CUB' },
    { label: 'Cyprus (€-Euro) - CYP' },
    { label: 'Czech Republic (Kč-Czech koruna) - CZE' },
    { label: 'Denmark (kr-Danish krone) - DNK' },
    { label: 'Djibouti (Fdj-Djiboutian franc) - DJI' },
    { label: 'Dominica (EC$-Eastern Caribbean dollar) - DMA' },
    { label: 'Dominican Republic (RD$-Dominican peso) - DOM' },
    { label: 'East Timor (US$-United States dollar) - TLS' },
    { label: 'Ecuador ($-United States dollar) - ECU' },
    { label: 'Egypt (E£-Egyptian pound) - EGY' },
    { label: 'El Salvador ($-United States dollar) - SLV' },
    { label: 'Equatorial Guinea (FCFA-Central African CFA franc) - GNQ' },
    { label: 'Eritrea (Nakfa-Eritrean nakfa) - ERI' },
    { label: 'Estonia (€-Euro) - EST' },
    { label: 'Eswatini (E-Eswatini lilangeni) - SWZ' },
    { label: 'Ethiopia (Br-Ethiopian birr) - ETH' },
    { label: 'Fiji ($-Fijian dollar) - FJI' },
    { label: 'Finland (€-Euro) - FIN' },
    { label: 'France (€-Euro) - FRA' },
    { label: 'Gabon (XAF-Central African CFA franc) - GAB' },
    { label: 'Gambia (D-Gambian dalasi) - GMB' },
    { label: 'Georgia (₾-Georgian lari) - GEO' },
    { label: 'Germany (€-Euro) - DEU' },
    { label: 'Ghana (₵-Ghanaian cedi) - GHA' },
    { label: 'Greece (€-Euro) - GRC' },
    { label: 'Grenada (EC$-Eastern Caribbean dollar) - GRD' },
    { label: 'Guatemala (Q-Guatemalan quetzal) - GTM' },
    { label: 'Guinea (FG-Guinean franc) - GIN' },
    { label: 'Guinea-Bissau (CFA franc-Central African CFA franc) - GNB' },
    { label: 'Guyana (G$-Guyanese dollar) - GUY' },
    { label: 'Haiti (Gourde-Haitian gourde) - HTI' },
    { label: 'Honduras (L- Honduran lempira) - HND' },
    { label: 'Hungary (Ft-Hungarian forint) - HUN' },
    { label: 'Iceland (kr-Icelandic króna) - ISL' },
    { label: 'India (₹-Indian rupee) - IND' },
    { label: 'Indonesia (Rp-Indonesian rupiah) - IDN' },
    { label: 'Iran (ریال-Iranian rial) - IRN' },
    { label: 'Iraq (ع.د-Iraqi dinar) - IRQ' },
    { label: 'Ireland (€-Euro) - IRL' },
    { label: 'Israel (₪-Israeli new shekel) - ISR' },
    { label: 'Italy (€-Euro) - ITA' },
    { label: 'Jamaica (J$-Jamaican dollar) - JAM' },
    { label: 'Japan (¥-Japanese yen) - JPN' },
    { label: 'Jordan (د.ا-Jordanian dinar) - JOR' },
    { label: 'Kazakhstan (KZT-Kazakhstani tenge) - KAZ' },
    { label: 'Kenya (KSh-Kenyan shilling) - KEN' },
    { label: 'Kiribati ($-Australian dollar) - KIR' },
    { label: 'Korea, North (₩-North Korean won) - PRK' },
    { label: 'Korea, South (₩-South Korean won) - KOR' },
    { label: 'Kosovo (€-Euro) - XKX' },
    { label: 'Kuwait (د.ك-Kuwaiti dinar) - KWT' },
    { label: 'Kyrgyzstan (Som-Kyrgyzstani som) - KGZ' },
    { label: 'Laos (₭-Lao kip) - LAO' },
    { label: 'Latvia (€-Euro) - LVA' },
    { label: 'Lebanon (ل.ل-Lebanese pound) - LBN' },
    { label: 'Lesotho (L-Lesotho loti) - LSO' },
    { label: 'Liberia (L-Liberian dollar) - LBR' },
    { label: 'Libya (ل.د-Libyan dinar) - LBY' },
    { label: 'Liechtenstein (CHF-Swiss franc) - LIE' },
    { label: 'Lithuania (€-Euro) - LTU' },
    { label: 'Luxembourg (€-Euro) - LUX' },
    { label: 'Madagascar (Ar-Malagasy ariary) - MDG' },
    { label: 'Malawi (MK-Malawian kwacha) - MWI' },
    { label: 'Malaysia (RM-Malaysian ringgit) - MYS' },
    { label: 'Maldives (Rf-Maldivian rufiyaa) - MDV' },
    { label: 'Mali (CFA franc-Central African CFA franc) - MLI' },
    { label: 'Malta (€-Euro) - MLT' },
    { label: 'Marshall Islands ($-United States dollar) - MHL' },
    { label: 'Mauritania (UM-Mauritanian ouguiya) - MRT' },
    { label: 'Mauritius (₨-Mauritian rupee) - MUS' },
    { label: 'Mexico ($-Mexican peso) - MEX' },
    { label: 'Micronesia (US$-United States dollar) - FSM' },
    { label: 'Moldova (L-Moldovan leu) - MDA' },
    { label: 'Monaco (€-Euro) - MCO' },
    { label: 'Mongolia (₮-Mongolian tögrög) - MNG' },
    { label: 'Montenegro (€-Euro) - MNE' },
    { label: 'Morocco (د.م.-Moroccan dirham) - MAR' },
    { label: 'Mozambique (MT-Mozambican metical) - MOZ' },
    { label: 'Myanmar (Ks-Burmese kyat) - MMR' },
    { label: 'Namibia (N$-Namibian dollar) - NAM' },
    { label: 'Nauru (A$-Australian dollar) - NRU' },
    { label: 'Nepal (₨-Nepalese rupee) - NPL' },
    { label: 'Netherlands (€-Euro) - NLD' },
    { label: 'New Zealand ($-New Zealand dollar) - NZL' },
    { label: 'Nicaragua (C$-Nicaraguan córdoba) - NIC' },
    { label: 'Niger (XOF-West African CFA franc) - NER' },
    { label: 'Nigeria (₦-Nigerian naira) - NGA' },
    { label: 'North Macedonia (ден-Macedonian denar) - MKD' },
    { label: 'Norway (kr-Norwegian krone) - NOR' },
    { label: 'Oman (ر.ع.-Omani rial) - OMN' },
    { label: 'Pakistan (₨-Pakistani rupee) - PAK' },
    { label: 'Palau ($-United States dollar) - PLW' },
    { label: 'Palestine (₪-Israeli new shekel) - PSE' },
    { label: 'Panama (B/-Panamanian balboa) - PAN' },
    { label: 'Papua New Guinea (K-Papua New Guinean kina) - PNG' },
    { label: 'Paraguay (₲-Paraguayan guaraní) - PRY' },
    { label: 'Peru (S/.-Peruvian sol) - PER' },
    { label: 'Philippines (₱-Philippine peso) - PHL' },
    { label: 'Poland (zł-Polish złoty) - POL' },
    { label: 'Portugal (€-Euro) - PRT' },
    { label: 'Qatar (ر.ق-Qatari riyal) - QAT' },
    { label: 'Romania (lei-Romanian leu) - ROU' },
    { label: 'Russia (₽-Russian ruble) - RUS' },
    { label: 'Rwanda (RF-Rwandan franc) - RWA' },
    { label: 'Saint Kitts and Nevis (EC$-Eastern Caribbean dollar) - KNA' },
    { label: 'Saint Lucia (EC$-Eastern Caribbean dollar) - LCA' },
    { label: 'Saint Vincent and the Grenadines (EC$-Eastern Caribbean dollar) - VCT' },
    { label: 'Samoa (WS$-Samoan tālā) - WSM' },
    { label: 'San Marino (€-Euro) - SMR' },
    { label: 'Sao Tome and Principe (Db-São Tomé and Príncipe dobra) - STP' },
    { label: 'Saudi Arabia (ر.س-Saudi riyal) - SAU' },
    { label: 'Senegal (CFA franc-Central African CFA franc) - SEN' },
    { label: 'Serbia (дин.-Serbian dinar) - SRB' },
    { label: 'Seychelles (₨-Seychellois rupee) - SYC' },
    { label: 'Sierra Leone (Le-Sierra Leonean leone) - SLE' },
    { label: 'Singapore (S$-Singapore dollar) - SGP' },
    { label: 'Slovakia (€-Euro) - SVK' },
    { label: 'Slovenia (€-Euro) - SVN' },
    { label: 'Solomon Islands (SI$-Solomon Islands dollar) - SLB' },
    { label: 'Somalia (Sh-Somali shilling) - SOM' },
    { label: 'South Africa (R-South African rand) - ZAF' },
    { label: 'South Sudan (SSP-South Sudanese pound) - SSD' },
    { label: 'Spain (€-Euro) - ESP' },
    { label: 'Sri Lanka (රු-Sri Lankan rupee) - LKA' },
    { label: 'Sudan (SDG-Sudanese pound) - SDN' },
    { label: 'Suriname (Sr-Surinamese dollar) - SUR' },
    { label: 'Sweden (kr-Swedish krona) - SWE' },
    { label: 'Switzerland (CHF-Swiss franc) - CHE' },
    { label: 'Syria (£-Syrian pound) - SYR' },
    { label: 'Taiwan (NT$-New Taiwan dollar) - TWN' },
    { label: 'Tajikistan (ЅМ-Tajikistani somoni) - TJK' },
    { label: 'Tanzania (Sh-Tanzanian shilling) - TZA' },
    { label: 'Thailand (฿-Thai baht) - THA' },
    { label: 'Togo (CFA franc-Central African CFA franc) - TGO' },
    { label: 'Tonga (T$-Tongan paʻanga) - TON' },
    { label: 'Trinidad and Tobago (TT$-Trinidad and Tobago dollar) - TTO' },
    { label: 'Tunisia (د.ت-Tunisian dinar) - TUN' },
    { label: 'Turkey (₺-Turkish lira) - TUR' },
    { label: 'Turkmenistan (TMT-Turkmenistan manat) - TKM' },
    { label: 'Tuvalu ($-Australian dollar) - TUV' },
    { label: 'Uganda (USh-Ugandan shilling) - UGA' },
    { label: 'Ukraine (₴-Ukrainian hryvnia) - UKR' },
    { label: 'United Arab Emirates (د.إ-United Arab Emirates dirham) - ARE' },
    { label: 'United Kingdom (£-British pound) - GBR' },
    { label: 'United States of America ($-United States dollar) - USA' },
    { label: 'Uruguay ($-Uruguayan peso) - URY' },
    { label: 'Uzbekistan (so‘m-Uzbekistani soʻm) - UZB' },
    { label: 'Vanuatu (VT-Vanuatu vatu) - VUT' },
    { label: 'Vatican City (€-Euro) - VAT' },
    { label: 'Venezuela (Bs.-Venezuelan bolívar soberano) - VEN' },
    { label: 'Vietnam (₫-Vietnamese đồng) - VNM' },
    { label: 'Yemen (﷼-Yemeni rial) - YEM' },
    { label: 'Zambia (ZK-Zambian kwacha) - ZMB' },
    { label: 'Zimbabwe (ZWL-Zimbabwean dollar) - ZWE' },
];

export const currency = [
    { label: "USD" }, // United States Dollar
    { label: "EUR" }, // Euro
    { label: "JPY" }, // Japanese Yen
    { label: "GBP" }, // British Pound Sterling
    { label: "AUD" }, // Australian Dollar
    { label: "CAD" }, // Canadian Dollar
    { label: "CHF" }, // Swiss Franc
    { label: "CNY" }, // Chinese Yuan Renminbi
    { label: "SEK" }, // Swedish Krona
    { label: "NZD" }, // New Zealand Dollar
    { label: "MXN" }, // Mexican Peso
    { label: "SGD" }, // Singapore Dollar
    { label: "HKD" }, // Hong Kong Dollar
    { label: "NOK" }, // Norwegian Krone
    { label: "KRW" }, // South Korean Won
    { label: "RUB" }, // Russian Ruble
    { label: "INR" }, // Indian Rupee
    { label: "BRL" }, // Brazilian Real
    { label: "ZAR" }, // South African Rand
    { label: "TRY" }, // Turkish Lira
];